### PR TITLE
Initial creation of the hugo-based website

### PR DESCRIPTION
**Pull request by mangelajo**
This commit imports a stripped down version of the website
inherited from the submariner project.

It provides basic Makefile, and github scripts for publishing,
setting up a GIT_DEPLOY_KEY secret (private ssh key) for this project
and and the public counterside on ovn-org.github.io will be necessary
for the "publish/deploy" part to work properly.

### CODE REVIEW

**Comment by mangelajo** [comment]
@numansiddique @russellb there it goes ;-)

**Comment by flavio-fernandes** [comment]
Nice!!!!

One nit: Consider merging https://github.com/matcornic/hugo-theme-learn/pull/372
to avoid this warning message:
```
Building sites … WARN 2020/03/10 15:05:30 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
```

**Comment by numansiddique** [comment]
Thanks Miguel. I'll go ahead and merge it :).

**Comment by mangelajo** [comment]
> Nice!!!!
> 
> One nit: Consider merging [matcornic/hugo-theme-learn#372](https://github.com/matcornic/hugo-theme-learn/pull/372)
> to avoid this warning message:
> 
> ```
> Building sites … WARN 2020/03/10 15:05:30 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
> ```

That's a good one :-) we can now fix it with another PR :-) I'll do the same to submariner-website, it was annoying and didn't have time to look for the fix :)

**Pull request merged**
