### PR TITLE
fix links

### PR DESCRIPTION
**Pull request by fsb4000**
I receive 404 without .html

изображение

### CODE REVIEW

**Comment by fsb4000** [comment]
I also sent my changes to dev@openvswitch.org: https://patchwork.ozlabs.org/project/ovn/patch/294911691847425@2nmvwtstv3l3allg.iva.yp-c.yandex.net/

**Comment by numansiddique** [comment]
LGTM

**Comment by almusil** [comment]
Hi, this is automatically generated and currently the automation is broken, it should be fixed once #63 is merged and triggered.

**Comment by fsb4000** [comment]
Great!

**Pull request closed without merging**
